name: nix-flake-check

on:
  pull_request:
  push:
    branches:
      - main
      - reboot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix️"
        uses: cachix/install-nix-action@v16

      - name: "Install Cachix️"
        uses: cachix/cachix-action@v10
        with:
          name: typelevel

      - name: "Nix Flake Check"
        run: nix -L flake check
